piVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
      tier: backend
  template:
    metadata:
      name: todo-app
      labels:
        app: todo-app
        tier: backend
    spec:
      containers:
        - name: todo-api
          image: gcr.io/cloud-school-project-310615/api-server:v1
          imagePullPolicy: Always
          env:
           - name: MONGO_URL
             value: mongodb://mongo:27017/todos-app
