apiVersion: v1
kind: Service
metadata:
  name: todo-client
  labels:
    app: todo-app
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: todo-app
    tier: frontend