apiVersion: v1
kind: Service
metadata:
  name: todo-client
  labels:
    app: todo-app
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: todo-app
    tier: frontend